### ISSUE TITLE
Provide multiple language server backends for different file types in frontend

### ISSUE THREAD

**Issue by PBug90** [prona-p4-learning-platform/learn-sdn-hub#13]
Make sure current implementation supports this issue or update code to do so.

For example:
* .py file extension uses a python language server
* .p4 file extension uses a p4 language server

**Comment by srieger1** [comment]
Still on it. However looked at multiple LSP implementations for Python and none of them was usable with jsonrpc-ws-proxy so far. Some of the LSPs are using C#, Java etc. which does not seem wise to also be deployed in the instance hosts. Hence I tried https://github.com/palantir/python-language-server. They also offer a jsonrpc proxy solution https://github.com/palantir/python-jsonrpc-server, but this cannot be run using "python <some-main.py> --stio". https://github.com/sourcegraph/python-langserver supports this, but seems to be deprecated/abandoned. Maybe need to dig deeper into https://github.com/palantir/python-language-server but currently low on time for that

**Comment by srieger1** [comment]
I need to correct myself. After some tests, https://github.com/palantir/python-language-server seems like the way to go! I overlooked, that it can be used directly by starting "pyls" without any call to some python file etc. Directly uses stdio this way, so python could be simply added to the LSP by running "pip install pyls" (or building python-language-server from source, as described in their repo. 

```
langservers:
  p4:
    - node
    - /home/p4/p4-vscode-extension/server/build/server.js
    - --stdio
  python:
    - pyls
```

@PBug90 however the lsp websocket connection seems to be disabled still in the current version? ;) So I could only test the start of the lsp.

**Comment by srieger1** [comment]
#45 addressed this issue. Maybe selection of language parser and language server could be made configurable based on the filetype/file extension in the future
