### ISSUE TITLE
admin page and course management

### ISSUE THREAD

**Issue by srieger1** [prona-p4-learning-platform/learn-sdn-hub#91]
- allow changes of running / persisted config, e.g.:
  - assignments (tasks, files, ...)
  - maybe introduce possibility to add courses, containing assignments
  - ...
- show runtime information
  - currently logged-in users
  - submissions/status
  - ...

**Comment by S-Schickentanz** [comment]
- [ ] Submission page
- [ ] Show submissions of each group / user
- [ ] Show (bonus) points for submission / user
- [ ] Possibly downloading a submission

**Comment by srieger1** [comment]
PR has been merged in develop and now in master, closing issue
